//! macOS Seatbelt isolation for rollouts and the verifier.
//!
//! Profile generation sits behind the [`Isolation`] trait for the reason the rationale
//! gives: Apple already marks `sandbox-exec` deprecated, so the fallback (rollouts in a
//! Linux VM) must be swappable. Codex CLI uses the same mechanism and the policy covers
//! the whole process tree, which is what makes it a real boundary where OpenCode's own
//! path rules are not — bash redirection can slip past those.

use std::path::{Path, PathBuf};

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::Result;

/// Knobs for the generated rollout profile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProfileConfig {
    /// Turn isolation off. Only for CI on non-macOS hosts; the daemon warns loudly.
    #[serde(default)]
    pub disabled: bool,
    /// Extra paths the task toolchain needs to read (e.g. a toolchain cache).
    #[serde(default)]
    pub extra_read_paths: Vec<PathBuf>,
    /// Extra writable paths beyond the work directory.
    #[serde(default)]
    pub extra_write_paths: Vec<PathBuf>,
    /// Rollouts need the network to reach Fireworks; the verifier usually does not.
    #[serde(default = "default_true")]
    pub allow_network_for_rollouts: bool,
    /// Codex's profile blocks most IOKit access, which broke Metal for GPU
    /// subprocesses. Flip this on if a task toolchain needs the GPU.
    #[serde(default)]
    pub allow_iokit: bool,
}

fn default_true() -> bool {
    true
}

impl Default for ProfileConfig {
    fn default() -> Self {
        Self {
            disabled: false,
            extra_read_paths: Vec::new(),
            extra_write_paths: Vec::new(),
            allow_network_for_rollouts: true,
            allow_iokit: false,
        }
    }
}

/// What a profile is being generated for.
#[derive(Debug, Clone)]
pub struct ProfileRequest {
    /// The only writable subtree (plus temp).
    pub work_dir: PathBuf,
    /// Paths that must be unreadable. The vault goes here for rollouts: the paper's
    /// ablation shows wiki access for the inference agent lowers final skill quality.
    pub deny_read: Vec<PathBuf>,
    /// Whether this process may reach the network.
    pub allow_network: bool,
}

/// Generates a policy and wraps commands in it.
#[async_trait]
pub trait Isolation: Send + Sync {
    /// Human-readable name, recorded in run metadata.
    fn name(&self) -> &'static str;

    /// Builds a command that runs `program` with `args` under the policy.
    async fn command(
        &self,
        request: &ProfileRequest,
        program: &str,
        args: &[String],
    ) -> Result<tokio::process::Command>;
}

/// `/usr/bin/sandbox-exec` with a generated SBPL profile.
pub struct Seatbelt {
    config: ProfileConfig,
    /// Where generated `.sb` files are written.
    profile_dir: PathBuf,
}

impl Seatbelt {
    pub fn new(config: ProfileConfig, profile_dir: impl Into<PathBuf>) -> Self {
        Self {
            config,
            profile_dir: profile_dir.into(),
        }
    }

    pub fn available() -> bool {
        Path::new("/usr/bin/sandbox-exec").exists()
    }

    /// Renders the SBPL text. Public so phase 0 can review the exact policy and so it
    /// can be diffed when a toolchain breaks under it.
    pub fn render(&self, request: &ProfileRequest) -> String {
        let mut p = String::new();
        p.push_str("(version 1)\n");
        p.push_str(";; generated by wikiskilld — rollout/verifier profile\n");
        p.push_str("(deny default)\n");
        p.push_str("(allow process-fork)\n");
        p.push_str("(allow signal (target same-sandbox))\n");
        p.push_str("(allow sysctl-read)\n");
        p.push_str("(allow mach-lookup)\n");
        p.push_str("(allow process-exec)\n");
        p.push_str("(allow file-read-metadata)\n\n");

        p.push_str(";; readable: the system, the toolchain and the work tree\n");
        p.push_str("(allow file-read*\n");
        for path in [
            Path::new("/usr"),
            Path::new("/bin"),
            Path::new("/sbin"),
            Path::new("/System"),
            Path::new("/Library"),
            Path::new("/opt"),
            Path::new("/private/etc"),
            Path::new("/private/var/db/dyld"),
            Path::new("/dev"),
        ] {
            p.push_str(&format!("  (subpath {})\n", quote(path)));
        }
        p.push_str(&format!("  (subpath {})\n", quote(&request.work_dir)));
        for path in &self.config.extra_read_paths {
            p.push_str(&format!("  (subpath {})\n", quote(path)));
        }
        p.push_str(")\n\n");

        p.push_str(";; writable: the work tree and temp only\n");
        p.push_str("(allow file-write*\n");
        p.push_str(&format!("  (subpath {})\n", quote(&request.work_dir)));
        p.push_str("  (subpath \"/private/tmp\")\n");
        p.push_str("  (subpath \"/private/var/tmp\")\n");
        p.push_str("  (subpath \"/private/var/folders\")\n");
        p.push_str("  (literal \"/dev/null\")\n");
        p.push_str("  (literal \"/dev/dtracehelper\")\n");
        p.push_str("  (regex #\"^/dev/tty\")\n");
        for path in &self.config.extra_write_paths {
            p.push_str(&format!("  (subpath {})\n", quote(path)));
        }
        p.push_str(")\n\n");

        // Deny rules come last: in SBPL the last matching rule wins, so these override
        // the broad allows above — including any work dir that nests the vault.
        if !request.deny_read.is_empty() {
            p.push_str(";; the inference agent must never read the wiki\n");
            p.push_str("(deny file-read* file-write*\n");
            for path in &request.deny_read {
                p.push_str(&format!("  (subpath {})\n", quote(path)));
            }
            p.push_str(")\n\n");
        }

        if request.allow_network {
            p.push_str("(allow network-outbound)\n(allow network-bind)\n");
        } else {
            p.push_str("(deny network*)\n");
        }

        if self.config.allow_iokit {
            p.push_str("(allow iokit-open)\n");
        }
        p
    }

    async fn profile_path(&self, request: &ProfileRequest, tag: &str) -> Result<PathBuf> {
        tokio::fs::create_dir_all(&self.profile_dir).await?;
        let path = self.profile_dir.join(format!("{tag}.sb"));
        tokio::fs::write(&path, self.render(request)).await?;
        Ok(path)
    }
}

#[async_trait]
impl Isolation for Seatbelt {
    fn name(&self) -> &'static str {
        "seatbelt"
    }

    async fn command(
        &self,
        request: &ProfileRequest,
        program: &str,
        args: &[String],
    ) -> Result<tokio::process::Command> {
        if self.config.disabled {
            tracing::warn!("sandbox.disabled is set — running {program} unisolated");
            let mut cmd = tokio::process::Command::new(program);
            cmd.args(args);
            return Ok(cmd);
        }
        if !Self::available() {
            anyhow::bail!(
                "/usr/bin/sandbox-exec is missing; set sandbox.disabled only if you \
                 accept running rollouts unisolated, or switch to the VM fallback"
            );
        }
        let tag = if request.allow_network {
            "rollout"
        } else {
            "verifier"
        };
        let profile = self.profile_path(request, tag).await?;
        let mut cmd = tokio::process::Command::new("/usr/bin/sandbox-exec");
        cmd.arg("-f").arg(profile).arg(program).args(args);
        Ok(cmd)
    }
}

/// No isolation. Used by tests and by non-macOS CI; never a default.
pub struct NoIsolation;

#[async_trait]
impl Isolation for NoIsolation {
    fn name(&self) -> &'static str {
        "none"
    }

    async fn command(
        &self,
        _request: &ProfileRequest,
        program: &str,
        args: &[String],
    ) -> Result<tokio::process::Command> {
        let mut cmd = tokio::process::Command::new(program);
        cmd.args(args);
        Ok(cmd)
    }
}

/// Picks Seatbelt on macOS with `sandbox-exec` present, otherwise refuses unless the
/// config explicitly disables isolation.
pub fn for_host(config: &ProfileConfig, profile_dir: impl Into<PathBuf>) -> Result<Box<dyn Isolation>> {
    if config.disabled {
        return Ok(Box::new(NoIsolation));
    }
    if Seatbelt::available() {
        Ok(Box::new(Seatbelt::new(config.clone(), profile_dir)))
    } else {
        anyhow::bail!(
            "no isolation mechanism available on this host: sandbox-exec is missing. \
             Use the Linux VM fallback or set sandbox.disabled explicitly."
        )
    }
}

fn quote(path: &Path) -> String {
    // SBPL string literals: escape backslashes and quotes.
    let s = path.to_string_lossy().replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{s}\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn request() -> ProfileRequest {
        ProfileRequest {
            work_dir: PathBuf::from("/tmp/wikiskill/work"),
            deny_read: vec![PathBuf::from("/Users/x/Vaults/Agents/WikiSkill")],
            allow_network: true,
        }
    }

    #[test]
    fn profile_denies_the_vault_after_allowing_the_work_tree() {
        let sb = Seatbelt::new(ProfileConfig::default(), "/tmp/profiles");
        let text = sb.render(&request());
        let allow_at = text.find("(allow file-read*").unwrap();
        let deny_at = text.find("(deny file-read* file-write*").unwrap();
        assert!(deny_at > allow_at, "last match wins, so deny must come last");
        assert!(text.contains("/Users/x/Vaults/Agents/WikiSkill"));
        assert!(text.starts_with("(version 1)\n"));
        assert!(text.contains("(deny default)"));
    }

    #[test]
    fn verifier_profile_has_no_network() {
        let sb = Seatbelt::new(ProfileConfig::default(), "/tmp/profiles");
        let mut req = request();
        req.allow_network = false;
        let text = sb.render(&req);
        assert!(text.contains("(deny network*)"));
        assert!(!text.contains("(allow network-outbound)"));
    }

    #[test]
    fn iokit_stays_denied_unless_asked_for() {
        let base = Seatbelt::new(ProfileConfig::default(), "/tmp/p");
        assert!(!base.render(&request()).contains("iokit-open"));
        let gpu = Seatbelt::new(
            ProfileConfig {
                allow_iokit: true,
                ..Default::default()
            },
            "/tmp/p",
        );
        assert!(gpu.render(&request()).contains("(allow iokit-open)"));
    }

    #[tokio::test]
    async fn seatbelt_wraps_the_command_in_sandbox_exec() {
        if !Seatbelt::available() {
            return;
        }
        let dir = tempfile::tempdir().unwrap();
        let sb = Seatbelt::new(ProfileConfig::default(), dir.path());
        let cmd = sb
            .command(&request(), "/bin/echo", &["hi".to_string()])
            .await
            .unwrap();
        assert_eq!(
            cmd.as_std().get_program().to_string_lossy(),
            "/usr/bin/sandbox-exec"
        );
        assert!(dir.path().join("rollout.sb").is_file());
    }

    #[tokio::test]
    #[cfg(target_os = "macos")]
    async fn a_real_sandboxed_process_cannot_read_the_denied_path() {
        if !Seatbelt::available() {
            return;
        }
        let dir = tempfile::tempdir().unwrap();
        let secret_dir = dir.path().join("vault");
        tokio::fs::create_dir_all(&secret_dir).await.unwrap();
        tokio::fs::write(secret_dir.join("index.md"), "wiki")
            .await
            .unwrap();
        let work = dir.path().join("work");
        tokio::fs::create_dir_all(&work).await.unwrap();

        let sb = Seatbelt::new(ProfileConfig::default(), dir.path().join("profiles"));
        let req = ProfileRequest {
            work_dir: work.canonicalize().unwrap(),
            deny_read: vec![secret_dir.canonicalize().unwrap()],
            allow_network: false,
        };
        let mut cmd = sb
            .command(
                &req,
                "/bin/cat",
                &[secret_dir
                    .canonicalize()
                    .unwrap()
                    .join("index.md")
                    .to_string_lossy()
                    .to_string()],
            )
            .await
            .unwrap();
        let out = cmd.output().await.unwrap();
        assert!(
            !out.status.success(),
            "sandboxed cat should not read the vault: {}",
            String::from_utf8_lossy(&out.stdout)
        );
    }
}
